//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Print_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electionType", Namespace="http://www.evoting.ch/xmlns/print/2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectionType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("electionIdentification", Order=0)]
        public string ElectionIdentification { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ListType> _list;
        
        [System.Xml.Serialization.XmlElementAttribute("list", Order=1)]
        public System.Collections.Generic.List<ListType> List
        {
            get
            {
                return _list;
            }
            set
            {
                _list = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the List collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListSpecified
        {
            get
            {
                return ((this.List != null) 
                            && (this.List.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectionType" /> class.</para>
        /// </summary>
        public ElectionType()
        {
            this._list = new System.Collections.Generic.List<ListType>();
            this._candidate = new System.Collections.Generic.List<CandidateType>();
            this._writeInPosition = new System.Collections.Generic.List<WriteInPositionType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("emptyList", Order=2)]
        public EmptyListType EmptyList { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CandidateType> _candidate;
        
        [System.Xml.Serialization.XmlElementAttribute("candidate", Order=3)]
        public System.Collections.Generic.List<CandidateType> Candidate
        {
            get
            {
                return _candidate;
            }
            set
            {
                _candidate = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Candidate collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CandidateSpecified
        {
            get
            {
                return ((this.Candidate != null) 
                            && (this.Candidate.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<WriteInPositionType> _writeInPosition;
        
        [System.Xml.Serialization.XmlElementAttribute("writeInPosition", Order=4)]
        public System.Collections.Generic.List<WriteInPositionType> WriteInPosition
        {
            get
            {
                return _writeInPosition;
            }
            set
            {
                _writeInPosition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the WriteInPosition collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WriteInPositionSpecified
        {
            get
            {
                return ((this.WriteInPosition != null) 
                            && (this.WriteInPosition.Count != 0));
            }
        }
    }
}
