//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Print_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("votingCardList", Namespace="http://www.evoting.ch/xmlns/print/2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("votingCardList", Namespace="http://www.evoting.ch/xmlns/print/2")]
    public partial class VotingCardList
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contest", Order=0)]
        public ContestType Contest { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Signature", Order=1, Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public EVoting.XmldSig.SignatureType Signature { get; set; }
    }
}
