//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("configuration", Namespace="http://www.evoting.ch/xmlns/config/6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("configuration", Namespace="http://www.evoting.ch/xmlns/config/6")]
    public partial class Configuration
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("header", Order=0)]
        public HeaderType Header { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contest", Order=1)]
        public ContestType Contest { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<AuthorizationType> _authorizations;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("authorizations", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("authorization", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<AuthorizationType> Authorizations
        {
            get
            {
                return _authorizations;
            }
            set
            {
                _authorizations = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Configuration" /> class.</para>
        /// </summary>
        public Configuration()
        {
            this._authorizations = new System.Collections.Generic.List<AuthorizationType>();
            this._register = new System.Collections.Generic.List<VoterType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VoterType> _register;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("register", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("voter", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<VoterType> Register
        {
            get
            {
                return _register;
            }
            set
            {
                _register = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("signature", Order=4, DataType="base64Binary")]
        public byte[] Signature { get; set; }
    }
}
