//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contestType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContestType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contestIdentification", Order=0)]
        public string ContestIdentification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contestDefaultLanguage", Order=1)]
        public LanguageType ContestDefaultLanguage { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contestDate", Order=2, DataType="date")]
        public System.DateTime ContestDate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ContestDescriptionInformationTypeContestDescriptionInfo> _contestDescription;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("contestDescription", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contestDescriptionInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<ContestDescriptionInformationTypeContestDescriptionInfo> ContestDescription
        {
            get
            {
                return _contestDescription;
            }
            set
            {
                _contestDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ContestType" /> class.</para>
        /// </summary>
        public ContestType()
        {
            this._contestDescription = new System.Collections.Generic.List<ContestDescriptionInformationTypeContestDescriptionInfo>();
            this._extendedAuthenticationKeys = new System.Collections.Generic.List<string>();
            this._electionGroupBallot = new System.Collections.Generic.List<ElectionGroupBallotType>();
            this._voteInformation = new System.Collections.Generic.List<VoteInformationType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("evotingFromDate", Order=4, DataType="dateTime")]
        public System.DateTime EvotingFromDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("evotingToDate", Order=5, DataType="dateTime")]
        public System.DateTime EvotingToDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("adminBoard", Order=6)]
        public AdminBoardType AdminBoard { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("electoralBoard", Order=7)]
        public ElectoralBoardType ElectoralBoard { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _extendedAuthenticationKeys;
        
        [System.Xml.Serialization.XmlArrayAttribute("extendedAuthenticationKeys", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("keyName", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<string> ExtendedAuthenticationKeys
        {
            get
            {
                return _extendedAuthenticationKeys;
            }
            set
            {
                _extendedAuthenticationKeys = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ExtendedAuthenticationKeys collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtendedAuthenticationKeysSpecified
        {
            get
            {
                return ((this.ExtendedAuthenticationKeys != null) 
                            && (this.ExtendedAuthenticationKeys.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionGroupBallotType> _electionGroupBallot;
        
        [System.Xml.Serialization.XmlElementAttribute("electionGroupBallot", Order=9)]
        public System.Collections.Generic.List<ElectionGroupBallotType> ElectionGroupBallot
        {
            get
            {
                return _electionGroupBallot;
            }
            set
            {
                _electionGroupBallot = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElectionGroupBallot collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectionGroupBallotSpecified
        {
            get
            {
                return ((this.ElectionGroupBallot != null) 
                            && (this.ElectionGroupBallot.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VoteInformationType> _voteInformation;
        
        [System.Xml.Serialization.XmlElementAttribute("voteInformation", Order=10)]
        public System.Collections.Generic.List<VoteInformationType> VoteInformation
        {
            get
            {
                return _voteInformation;
            }
            set
            {
                _voteInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the VoteInformation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VoteInformationSpecified
        {
            get
            {
                return ((this.VoteInformation != null) 
                            && (this.VoteInformation.Count != 0));
            }
        }
    }
}
