//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("listType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("listIdentification", Order=0)]
        public string ListIdentification { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(6)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("listIndentureNumber", Order=1)]
        public string ListIndentureNumber { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ListDescriptionInformationTypeListDescriptionInfo> _listDescription;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("listDescription", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listDescriptionInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<ListDescriptionInformationTypeListDescriptionInfo> ListDescription
        {
            get
            {
                return _listDescription;
            }
            set
            {
                _listDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ListType" /> class.</para>
        /// </summary>
        public ListType()
        {
            this._listDescription = new System.Collections.Generic.List<ListDescriptionInformationTypeListDescriptionInfo>();
            this._candidatePosition = new System.Collections.Generic.List<CandidatePositionType>();
            this._varListText1 = new System.Collections.Generic.List<VarListTextInfoType>();
            this._varListText2 = new System.Collections.Generic.List<VarListTextInfoType>();
            this._displayListLine1 = new System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo>();
            this._displayListLine2 = new System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo>();
            this._displayListLine3 = new System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo>();
            this._displayListLine4 = new System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo>();
            this._displayListLine5 = new System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 120.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "1", "120", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("listOrderOfPrecedence", Order=3)]
        public byte ListOrderOfPrecedence { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("listEmpty", Order=4)]
        public bool ListEmpty { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CandidatePositionType> _candidatePosition;
        
        [System.Xml.Serialization.XmlElementAttribute("candidatePosition", Order=5)]
        public System.Collections.Generic.List<CandidatePositionType> CandidatePosition
        {
            get
            {
                return _candidatePosition;
            }
            set
            {
                _candidatePosition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CandidatePosition collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CandidatePositionSpecified
        {
            get
            {
                return ((this.CandidatePosition != null) 
                            && (this.CandidatePosition.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VarListTextInfoType> _varListText1;
        
        [System.Xml.Serialization.XmlArrayAttribute("varListText1", Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("varListTextInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<VarListTextInfoType> VarListText1
        {
            get
            {
                return _varListText1;
            }
            set
            {
                _varListText1 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the VarListText1 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VarListText1Specified
        {
            get
            {
                return ((this.VarListText1 != null) 
                            && (this.VarListText1.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VarListTextInfoType> _varListText2;
        
        [System.Xml.Serialization.XmlArrayAttribute("varListText2", Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("varListTextInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<VarListTextInfoType> VarListText2
        {
            get
            {
                return _varListText2;
            }
            set
            {
                _varListText2 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the VarListText2 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VarListText2Specified
        {
            get
            {
                return ((this.VarListText2 != null) 
                            && (this.VarListText2.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> _displayListLine1;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("displayListLine1", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayLineInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> DisplayListLine1
        {
            get
            {
                return _displayListLine1;
            }
            set
            {
                _displayListLine1 = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> _displayListLine2;
        
        [System.Xml.Serialization.XmlArrayAttribute("displayListLine2", Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayLineInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> DisplayListLine2
        {
            get
            {
                return _displayListLine2;
            }
            set
            {
                _displayListLine2 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DisplayListLine2 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayListLine2Specified
        {
            get
            {
                return ((this.DisplayListLine2 != null) 
                            && (this.DisplayListLine2.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> _displayListLine3;
        
        [System.Xml.Serialization.XmlArrayAttribute("displayListLine3", Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayLineInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> DisplayListLine3
        {
            get
            {
                return _displayListLine3;
            }
            set
            {
                _displayListLine3 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DisplayListLine3 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayListLine3Specified
        {
            get
            {
                return ((this.DisplayListLine3 != null) 
                            && (this.DisplayListLine3.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> _displayListLine4;
        
        [System.Xml.Serialization.XmlArrayAttribute("displayListLine4", Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayLineInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> DisplayListLine4
        {
            get
            {
                return _displayListLine4;
            }
            set
            {
                _displayListLine4 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DisplayListLine4 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayListLine4Specified
        {
            get
            {
                return ((this.DisplayListLine4 != null) 
                            && (this.DisplayListLine4.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> _displayListLine5;
        
        [System.Xml.Serialization.XmlArrayAttribute("displayListLine5", Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayLineInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<DisplayLineInformationTypeDisplayLineInfo> DisplayListLine5
        {
            get
            {
                return _displayListLine5;
            }
            set
            {
                _displayListLine5 = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DisplayListLine5 collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayListLine5Specified
        {
            get
            {
                return ((this.DisplayListLine5 != null) 
                            && (this.DisplayListLine5.Count != 0));
            }
        }
    }
}
