//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("voterTypeType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    public enum VoterTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("SWISSRESIDENT")]
        Swissresident,
        
        [System.Xml.Serialization.XmlEnumAttribute("SWISSABROAD")]
        Swissabroad,
        
        [System.Xml.Serialization.XmlEnumAttribute("FOREIGNER")]
        Foreigner,
    }
}
