//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.XmldSig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DSAKeyValueType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DsaKeyValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("P", Order=0, DataType="base64Binary")]
        public byte[] P { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Q", Order=1, DataType="base64Binary")]
        public byte[] Q { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("G", Order=2, DataType="base64Binary")]
        public byte[] G { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Y", Order=3, DataType="base64Binary")]
        public byte[] Y { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("J", Order=4, DataType="base64Binary")]
        public byte[] J { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Seed", Order=5, DataType="base64Binary")]
        public byte[] Seed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PgenCounter", Order=6, DataType="base64Binary")]
        public byte[] PgenCounter { get; set; }
    }
}
