//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.XmldSig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PGPDataType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class PgpDataType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", Order=0, DataType="base64Binary")]
        public byte[] PgpKeyId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<byte[]> _pgpKeyPacket;
        
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", Order=1, DataType="base64Binary")]
        public System.Collections.Generic.List<byte[]> PgpKeyPacket
        {
            get
            {
                return _pgpKeyPacket;
            }
            set
            {
                _pgpKeyPacket = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PgpKeyPacket collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PgpKeyPacketSpecified
        {
            get
            {
                return ((this.PgpKeyPacket != null) 
                            && (this.PgpKeyPacket.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PgpDataType" /> class.</para>
        /// </summary>
        public PgpDataType()
        {
            this._pgpKeyPacket = new System.Collections.Generic.List<byte[]>();
            this._any = new System.Collections.Generic.List<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<System.Xml.XmlElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Collections.Generic.List<System.Xml.XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
    }
}
