//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.XmldSig
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("X509DataType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<X509IssuerSerialType> _x509IssuerSerial;
        
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", Order=0)]
        public System.Collections.Generic.List<X509IssuerSerialType> X509IssuerSerial
        {
            get
            {
                return _x509IssuerSerial;
            }
            set
            {
                _x509IssuerSerial = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the X509IssuerSerial collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X509IssuerSerialSpecified
        {
            get
            {
                return ((this.X509IssuerSerial != null) 
                            && (this.X509IssuerSerial.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="X509DataType" /> class.</para>
        /// </summary>
        public X509DataType()
        {
            this._x509IssuerSerial = new System.Collections.Generic.List<X509IssuerSerialType>();
            this._x509Ski = new System.Collections.Generic.List<byte[]>();
            this._x509SubjectName = new System.Collections.Generic.List<string>();
            this._x509Certificate = new System.Collections.Generic.List<byte[]>();
            this._x509Crl = new System.Collections.Generic.List<byte[]>();
            this._any = new System.Collections.Generic.List<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<byte[]> _x509Ski;
        
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", Order=1, DataType="base64Binary")]
        public System.Collections.Generic.List<byte[]> X509Ski
        {
            get
            {
                return _x509Ski;
            }
            set
            {
                _x509Ski = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the X509Ski collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X509SkiSpecified
        {
            get
            {
                return ((this.X509Ski != null) 
                            && (this.X509Ski.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _x509SubjectName;
        
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", Order=2)]
        public System.Collections.Generic.List<string> X509SubjectName
        {
            get
            {
                return _x509SubjectName;
            }
            set
            {
                _x509SubjectName = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the X509SubjectName collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X509SubjectNameSpecified
        {
            get
            {
                return ((this.X509SubjectName != null) 
                            && (this.X509SubjectName.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<byte[]> _x509Certificate;
        
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", Order=3, DataType="base64Binary")]
        public System.Collections.Generic.List<byte[]> X509Certificate
        {
            get
            {
                return _x509Certificate;
            }
            set
            {
                _x509Certificate = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the X509Certificate collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X509CertificateSpecified
        {
            get
            {
                return ((this.X509Certificate != null) 
                            && (this.X509Certificate.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<byte[]> _x509Crl;
        
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", Order=4, DataType="base64Binary")]
        public System.Collections.Generic.List<byte[]> X509Crl
        {
            get
            {
                return _x509Crl;
            }
            set
            {
                _x509Crl = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the X509Crl collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool X509CrlSpecified
        {
            get
            {
                return ((this.X509Crl != null) 
                            && (this.X509Crl.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<System.Xml.XmlElement> _any;
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Collections.Generic.List<System.Xml.XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Any collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return ((this.Any != null) 
                            && (this.Any.Count != 0));
            }
        }
    }
}
