//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ballotType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BallotType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ballotIdentification", Order=0)]
        public string BallotIdentification { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 120.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "1", "120", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ballotPosition", Order=1)]
        public byte BallotPosition { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<BallotDescriptionInformationTypeBallotDescriptionInfo> _ballotDescription;
        
        [System.Xml.Serialization.XmlArrayAttribute("ballotDescription", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ballotDescriptionInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<BallotDescriptionInformationTypeBallotDescriptionInfo> BallotDescription
        {
            get
            {
                return _ballotDescription;
            }
            set
            {
                _ballotDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the BallotDescription collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BallotDescriptionSpecified
        {
            get
            {
                return ((this.BallotDescription != null) 
                            && (this.BallotDescription.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BallotType" /> class.</para>
        /// </summary>
        public BallotType()
        {
            this._ballotDescription = new System.Collections.Generic.List<BallotDescriptionInformationTypeBallotDescriptionInfo>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("standardBallot", Order=3)]
        public StandardBallotType StandardBallot { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("variantBallot", Order=4)]
        public VariantBallotType VariantBallot { get; set; }
    }
}
