//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("incumbentType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncumbentType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("incumbent", Order=0)]
        public bool Incumbent { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<IncumbentTextInfoType> _incumbentText;
        
        [System.Xml.Serialization.XmlArrayAttribute("incumbentText", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("incumbentTextInfo", Namespace="http://www.evoting.ch/xmlns/config/6")]
        public System.Collections.Generic.List<IncumbentTextInfoType> IncumbentText
        {
            get
            {
                return _incumbentText;
            }
            set
            {
                _incumbentText = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IncumbentText collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncumbentTextSpecified
        {
            get
            {
                return ((this.IncumbentText != null) 
                            && (this.IncumbentText.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="IncumbentType" /> class.</para>
        /// </summary>
        public IncumbentType()
        {
            this._incumbentText = new System.Collections.Generic.List<IncumbentTextInfoType>();
        }
    }
}
