//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sexType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    public enum SexType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("MALE")]
        Male,
        
        [System.Xml.Serialization.XmlEnumAttribute("FEMALE")]
        Female,
        
        [System.Xml.Serialization.XmlEnumAttribute("UNDEFINED")]
        Undefined,
    }
}
