//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("variantBallotType", Namespace="http://www.evoting.ch/xmlns/config/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VariantBallotType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<StandardQuestionType> _standardQuestion;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("standardQuestion", Order=0)]
        public System.Collections.Generic.List<StandardQuestionType> StandardQuestion
        {
            get
            {
                return _standardQuestion;
            }
            set
            {
                _standardQuestion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VariantBallotType" /> class.</para>
        /// </summary>
        public VariantBallotType()
        {
            this._standardQuestion = new System.Collections.Generic.List<StandardQuestionType>();
            this._tieBreakQuestion = new System.Collections.Generic.List<TieBreakQuestionType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<TieBreakQuestionType> _tieBreakQuestion;
        
        [System.Xml.Serialization.XmlElementAttribute("tieBreakQuestion", Order=1)]
        public System.Collections.Generic.List<TieBreakQuestionType> TieBreakQuestion
        {
            get
            {
                return _tieBreakQuestion;
            }
            set
            {
                _tieBreakQuestion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TieBreakQuestion collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TieBreakQuestionSpecified
        {
            get
            {
                return ((this.TieBreakQuestion != null) 
                            && (this.TieBreakQuestion.Count != 0));
            }
        }
    }
}
