//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electionRulesExplanationType", Namespace="http://www.evoting.ch/xmlns/config/7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectionRulesExplanationType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionRulesExplanationTypeDisplayLineInfo> _displayLineInfo;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("displayLineInfo", Order=0)]
        public System.Collections.Generic.List<ElectionRulesExplanationTypeDisplayLineInfo> DisplayLineInfo
        {
            get
            {
                return _displayLineInfo;
            }
            set
            {
                _displayLineInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectionRulesExplanationType" /> class.</para>
        /// </summary>
        public ElectionRulesExplanationType()
        {
            this._displayLineInfo = new System.Collections.Generic.List<ElectionRulesExplanationTypeDisplayLineInfo>();
        }
    }
}
