//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electionType", Namespace="http://www.evoting.ch/xmlns/config/7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectionType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("electionIdentification", Order=0)]
        public string ElectionIdentification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("typeOfElection", Order=1)]
        public ElectionTypeTypeOfElection TypeOfElection { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionRulesExplanationTypeDisplayLineInfo> _electionRulesExplanation;
        
        [System.Xml.Serialization.XmlArrayAttribute("electionRulesExplanation", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("displayLineInfo", Namespace="http://www.evoting.ch/xmlns/config/7")]
        public System.Collections.Generic.List<ElectionRulesExplanationTypeDisplayLineInfo> ElectionRulesExplanation
        {
            get
            {
                return _electionRulesExplanation;
            }
            set
            {
                _electionRulesExplanation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElectionRulesExplanation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectionRulesExplanationSpecified
        {
            get
            {
                return ((this.ElectionRulesExplanation != null) 
                            && (this.ElectionRulesExplanation.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectionType" /> class.</para>
        /// </summary>
        public ElectionType()
        {
            this._electionRulesExplanation = new System.Collections.Generic.List<ElectionRulesExplanationTypeDisplayLineInfo>();
            this._electionDescription = new System.Collections.Generic.List<ElectionDescriptionInformationTypeElectionDescriptionInfo>();
            this._referencedElection = new System.Collections.Generic.List<ReferencedElectionInformationType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionDescriptionInformationTypeElectionDescriptionInfo> _electionDescription;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("electionDescription", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("electionDescriptionInfo", Namespace="http://www.evoting.ch/xmlns/config/7")]
        public System.Collections.Generic.List<ElectionDescriptionInformationTypeElectionDescriptionInfo> ElectionDescription
        {
            get
            {
                return _electionDescription;
            }
            set
            {
                _electionDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 500.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "1", "500", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("electionPosition", Order=4)]
        public ushort ElectionPosition { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// <para xml:lang="en">Maximum inclusive value: 150.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "1", "150", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("numberOfMandates", Order=5)]
        public byte NumberOfMandates { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("writeInsAllowed", Order=6)]
        public bool WriteInsAllowed { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("candidateAccumulation", Order=7)]
        public ElectionTypeCandidateAccumulation CandidateAccumulation { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 1.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "0", "1", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("minimalCandidateSelectionInList", Order=8)]
        public byte MinimalCandidateSelectionInList { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ReferencedElectionInformationType> _referencedElection;
        
        [System.Xml.Serialization.XmlElementAttribute("referencedElection", Order=9)]
        public System.Collections.Generic.List<ReferencedElectionInformationType> ReferencedElection
        {
            get
            {
                return _referencedElection;
            }
            set
            {
                _referencedElection = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ReferencedElection collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencedElectionSpecified
        {
            get
            {
                return ((this.ReferencedElection != null) 
                            && (this.ReferencedElection.Count != 0));
            }
        }
    }
}
