//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("languageType", Namespace="http://www.evoting.ch/xmlns/config/7")]
    public enum LanguageType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("de")]
        De,
        
        [System.Xml.Serialization.XmlEnumAttribute("fr")]
        Fr,
        
        [System.Xml.Serialization.XmlEnumAttribute("it")]
        It,
        
        [System.Xml.Serialization.XmlEnumAttribute("rm")]
        Rm,
    }
}
