//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("positionTextInfoType", Namespace="http://www.evoting.ch/xmlns/config/7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PositionTextInfoType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<PositionTextInfoTypePositionText> _positionText;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("positionText", Order=0)]
        public System.Collections.Generic.List<PositionTextInfoTypePositionText> PositionText
        {
            get
            {
                return _positionText;
            }
            set
            {
                _positionText = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PositionTextInfoType" /> class.</para>
        /// </summary>
        public PositionTextInfoType()
        {
            this._positionText = new System.Collections.Generic.List<PositionTextInfoTypePositionText>();
        }
    }
}
