//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardAnswerTypeStandardAnswerType", Namespace="http://www.evoting.ch/xmlns/config/7", AnonymousType=true)]
    public enum StandardAnswerTypeStandardAnswerType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("YES")]
        Yes,
        
        [System.Xml.Serialization.XmlEnumAttribute("NO")]
        No,
        
        [System.Xml.Serialization.XmlEnumAttribute("EMPTY")]
        Empty,
        
        [System.Xml.Serialization.XmlEnumAttribute("UNDEFINED")]
        Undefined,
    }
}
