//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace EVoting.Config_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("voterType", Namespace="http://www.evoting.ch/xmlns/config/7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoterType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("voterIdentification", Order=0)]
        public string VoterIdentification { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [\w\-_]{1,50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[\\w\\-_]{1,50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("authorization", Order=1)]
        public string Authorization { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ExtendedAuthenticationKeyType> _extendedAuthenticationKeys;
        
        [System.Xml.Serialization.XmlArrayAttribute("extendedAuthenticationKeys", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("extendedAuthenticationKey", Namespace="http://www.evoting.ch/xmlns/config/7")]
        public System.Collections.Generic.List<ExtendedAuthenticationKeyType> ExtendedAuthenticationKeys
        {
            get
            {
                return _extendedAuthenticationKeys;
            }
            set
            {
                _extendedAuthenticationKeys = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ExtendedAuthenticationKeys collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtendedAuthenticationKeysSpecified
        {
            get
            {
                return ((this.ExtendedAuthenticationKeys != null) 
                            && (this.ExtendedAuthenticationKeys.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VoterType" /> class.</para>
        /// </summary>
        public VoterType()
        {
            this._extendedAuthenticationKeys = new System.Collections.Generic.List<ExtendedAuthenticationKeyType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sex", Order=3)]
        public SexType Sex { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("voterType", Order=4)]
        public VoterTypeType VoterTypeProperty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("person", Order=5)]
        public PersonType Person { get; set; }
    }
}
